name: Scan de Sécurité SAST
on: [push, pull_request]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3
      - name: Scan Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
